# Generated by Django 4.2.30 on 2026-07-10 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务名称')),
                ('description', models.TextField(verbose_name='服务描述')),
                ('category', models.CharField(max_length=50, verbose_name='服务分类')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('duration', models.IntegerField(help_text='单位：分钟', verbose_name='服务时长')),
                ('address', models.CharField(max_length=200, verbose_name='服务地址')),
                ('city', models.CharField(default='武汉', max_length=50, verbose_name='城市')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('views', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('rating', models.FloatField(default=0.0, verbose_name='评分')),
                ('review_count', models.IntegerField(default=0, verbose_name='评价数量')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='服务图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='服务提供者')),
            ],
            options={
                'verbose_name': '服务',
                'verbose_name_plural': '服务',
                'db_table': 'services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', '周一'), ('tuesday', '周二'), ('wednesday', '周三'), ('thursday', '周四'), ('friday', '周五'), ('saturday', '周六'), ('sunday', '周日')], max_length=20, verbose_name='星期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('is_available', models.BooleanField(default=True, verbose_name='是否可用')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to=settings.AUTH_USER_MODEL, verbose_name='服务提供者')),
            ],
            options={
                'verbose_name': '可用时段',
                'verbose_name_plural': '可用时段',
                'db_table': 'time_slots',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('provider', 'day_of_week', 'start_time')},
            },
        ),
    ]
