# Generated by Django 4.2.30 on 2026-07-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'service_categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='work_end',
            field=models.TimeField(blank=True, null=True, verbose_name='345267245344275234347273223346235237346227266351227264'),
        ),
        migrations.AddField(
            model_name='service',
            name='work_start',
            field=models.TimeField(blank=True, null=True, verbose_name='345267245344275234345274200345247213346227266351227264'),
        ),
    ]
