# Generated by Django 4.2.30 on 2026-07-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_trade_no',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='支付宝交易号'),
        ),
    ]
