# Generated by Django 4.2.30 on 2026-07-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='是否审核通过'),
        ),
    ]
